// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziymsklhoxwcxsmuutwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppeW1za2xob3h3Y3hzbXV1dHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NTMwMzcsImV4cCI6MjA1MTIyOTAzN30.vmm7i1HCeg_e3LHaCm5Mm2r6iVT9zLM5CTz-gVDZfzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);